
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080


FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["FMS.API/FMS.API.csproj", "FMS.API/"]
RUN dotnet restore "FMS.API/FMS.API.csproj"

COPY . .
WORKDIR "/src/FMS.API"
RUN dotnet publish "FMS.API.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "FMS.API.dll"]
